### ISSUE TITLE
Error: array subscript has type 'char' [-Weerror-char-subscripts] Cardputer.cpp:89:19

### ISSUE THREAD

**Issue by collossuspilot55** [romalik/m5cardputer_doom#1]
`    for (auto& i : __keyboard->keysState().values) {
        new_state[i] = 1;
        if(i == 's') {
            scale = !scale;
        }
    }
`
The error is with the ` new_state[i] = 1;`  specifically the i
This is stopping the compilation and I don't know why its throwing this error.

**Comment by hsnewman** [comment]
I'm getting this too! Anyway you can post the .bin?

**Comment by collossuspilot55** [comment]
The issue was fixed this morning, I'll try recompiling later and if it stops throwing the error I'll close the issue.

**Comment by collossuspilot55** [comment]
This issue was fixed, but I am still running into issues
