### ISSUE TITLE
New error [does not compile on esp-idf 5.2.1]

### ISSUE THREAD

**Issue by hsnewman** [romalik/m5cardputer_doom#2]
I just downloaded the newest version and am getting:

cc1.exe: some warnings being treated as errors
[1381/1435] Building CXX object esp-idf/LovyanGFX/CMakeFiles/__idf_LovyanGFX.dir/src/lgfx/v1/LGFXBase.cpp.obj
ninja: build stopped: subcommand failed.
HINT: The issue is better to resolve by replacing format specifiers to 'PRI'-family macros (include <inttypes.h> header file).
ninja failed with exit code 1, output of the command is in the C:\m5cardputer_doom\build\log\idf_py_stderr_output_372 and C:\m5cardputer_doom\build\log\idf_py_stdout_output_372

**Comment by romalik** [comment]
Interesting, I do not get this error on my toolchain. Which version of idf are you building against? I am using idf version "ESP-IDF v4.4.6" on Ubuntu, maybe this will help. Anyways i'm working rn on final features and will release the binary soon.

**Comment by hsnewman** [comment]
I'm on:
idf.py -v
Checking Python dependencies...
Constraint file: C:\Espressif\espidf.constraints.v5.2.txt
Requirement files:
 - C:\Espressif\frameworks\esp-idf-v5.2.1\tools\requirements\requirements.core.txt
Python being checked: C:\Espressif\python_env\idf5.2_py3.11_env\Scripts\python.exe
Python requirements are satisfied.

5.2.1?

**Comment by romalik** [comment]
Will try to reproduce later on newer idf

**Comment by hsnewman** [comment]
I'll uninstall and reinstall the version ESP-IDF v4.4.6

**Comment by hsnewman** [comment]
I compiled it under 4.4.6 and was able to flash
