### ISSUE TITLE
M5Launcher reports error

### ISSUE THREAD

**Issue by andypiper** [romalik/m5cardputer_doom#6]
When I install this to SD card or try to install OTA on M5Launcher where it is listed, I see an error. How can this be resolved?

**Comment by Dev-Cwsc** [comment]
@andypiper actually it is not an issue. You must use a different partition scheme.  Restart your device and open M5launcher menu, go to cfg->part change->doom, then try to install again. For me it works after doing this.

**Comment by andypiper** [comment]
You are right, thank you. It works. This should be in the README, though!
